
PACKAGE_MANAGER=pacman

# TOGGLE PROGAM AND CONFIG INSTALLATION (0 - DISABLED, 1 - ENABLED):
    INPUTRC=1
    BASHRC=1
    SWAY=0
    KITTY=1
    NEOVIM=1
    NEOVIM_FT=1
    QUTEBROWSER=0
    ZATHURA=1
    RANGER=1
